# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      grub.enable = false;
      generic-extlinux-compatible.enable = true;
    };
    initrd = {
      availableKernelModules = [ "nvme" "nvme_core" "phy-rockchip-naneng-combphy" "phy-rockchip-snps-pcie3" ];
    };
    kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = [ "debug" "console=ttyS2,1500000" "root=/dev/nvme0n1p1" "rootfstype=btrfs" ];
    supportedFilesystems = pkgs.lib.mkForce [ "bcachefs" "btrfs" "cifs" "f2fs" "jfs" "ntfs" "reiserfs" "vfat" "xfs" "ext2" ];
  };

  hardware = {
    deviceTree = {
      enable = true;
      name = "rockchip/rk3588s-odroid-m2.dtb";
    };
  };

  networking = {
    useDHCP = lib.mkDefault true;
    networkmanager.enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
