ZSH_THEME_RANDOM_IGNORED=(smt humza)

eval "$(direnv hook zsh)"

copy_function() {
  test -n "$(declare -f "$1")" || return
  eval "${_/$1/$2}"
}

copy_function _direnv_hook _direnv_hook__old

_direnv_hook() {
  _direnv_hook__old "$@" 2> >( egrep -v -e '^direnv: (export)' )
};

